insert into engagements values (NULL,
"Pride",
"Mann",
"Kristopher",
"kris.mann@example.com",
"Pride Office",
"123 Main St",
"",
"Seattle",
"WA",
"98101",
"2019-01-2",
"Board annual retreat 2 hour time slot",
"10",
"Knowledgeable and supportin",
"Board members and staff. Some sister organization representatives",
"Yes",
"Yes",
"Location has everything - bring your own laptop or thumbdrive",
"Yes",
"Parking at location. Bring parking ticket in for validation"
)
insert into engagements values (NULL,
"NWAF",
"Dude",
"guy",
"guy.dude@example.com",
"Pride Office",
"123 Main St",
"",
"Seattle",
"WA",
98101,
"2019-01-2",
"Board annual retreat 2 hour time slot",
10,
"Knowledgeable and supportin",
"Board members and staff. Some sister organization representatives",
"Yes",
"Yes",
"Location has everything - bring your own laptop or thumbdrive",
"Yes",
"Parking at location. Bring parking ticket in for validation"
)